### PR TITLE
Daryl bug fixes

### LINKED ISSUE #88: Sanitize data in save file
1. Tasks with clashing times can be loaded from save file
2. Recurring tasks with by dates can be loaded from save file

### PR DESCRIPTION
**Pull request by thedarie**
**Linked Storage with TaskList**
- Will fix most / all issues regarding invalid inputs in save files

**Removed `index` field in save file**
- No real use for it since the index is updated everytime a new task is added

**Added by date and by time**
**Added checks for do date** (do datetime must be after datetime when entering command)
**Allow by date for recurring tasks**
- By allowing by date for recurring tasks, the `frequency` field in the save file can be removed (there is no longer any need to differentiate recurring and non-recurring)
- By date will be incremented just like do date

Fixes #88, #100, #104, #112, #114, #122, #124

### CODE REVIEW

File: src/main/java/seedu/sherpass/task/TaskList.java [hunk 1]
```diff
@@ -302,12 +305,7 @@ public void editRepeatedTasks(int editIndex, String taskDescription,
 
         long startDateOffset = calculateOffsetOfDate(firstTask.getDoOnStartDateTime(), doOnStartDateTime);
         long endDateOffset = calculateOffsetOfDate(firstTask.getDoOnEndDateTime(), doOnEndDateTime);
-        long byDateOffset;
-        if (doOnStartDateTime == null) {
-            byDateOffset = calculateOffsetOfDate(firstTask.getDoOnStartDateTime(), byDateTime);
-        } else {
-            byDateOffset = calculateOffsetOfDate(doOnStartDateTime, byDateTime);
-        }
+        long byDateOffset = calculateOffsetOfDate(doOnStartDateTime, byDateTime);
```
Comment (jltha) [inline src/main/java/seedu/sherpass/task/TaskList.java:311]: Do we need to calculate such an offset? I was thinking that it doesn't really matter even if the user gives the same input, since we'll still overwrite the existing doOnStartDateTime and doOnEndDateTime. Its fine even if the same inputs were given.

File: src/main/java/seedu/sherpass/task/TaskList.java [hunk 2]
```diff
@@ -179,83 +188,137 @@ public void checkDateTimeClash(ArrayList<Task> taskList, Task taskToCheck)
...
     }
 
+    private void checkTask(Task newTask) throws InvalidInputException {
+        if (newTask.getDoOnStartDateTime().isBefore(LocalDateTime.now())) {
+            throw new InvalidInputException(ERROR_START_DATE_IN_THE_PAST_MESSAGE);
+        } else if (newTask.getDoOnStartDateTime().isAfter(newTask.getDoOnEndDateTime())) {
+            throw new InvalidInputException(ERROR_START_AFTER_END_TIME_MESSAGE);
+        } else if (newTask.getByDateTime() != null
+                && newTask.getByDateTime().isBefore(newTask.getDoOnStartDateTime())) {
+            throw new InvalidInputException(ERROR_BY_DATE_BEFORE_START_DATE_MESSAGE);
```
Comment (jltha) [inline src/main/java/seedu/sherpass/task/TaskList.java:203]: These are checked for in the checkDateTimeClash method, specifically isByDateBeforeDoOnDate() and isStartTimeClashWithEndTime()

File: src/main/java/seedu/sherpass/task/TaskList.java (hunk 1 above)
Comment (thedarie) [reply src/main/java/seedu/sherpass/task/TaskList.java:311]: i think your looking at an old commit but the motivation to use offset instead of an absolute date can be shown
assume you have a recurring task:
5th april 2022 
6th april 2022
7th april 2022

say the 6th april task is deleted, we are left with the 5th and 7th april tasks. if the user decides to edit 5th april to 10th april, without offset the tasklist becomes like this
10th april
11th april

whereas if you use offset it becomes
10th april
12th april

also, by using offset we can make do without the 'frequency' attribute since we just need to shift the dates by the calculated offset

File: src/main/java/seedu/sherpass/task/TaskList.java [hunk 3]
```diff
@@ -179,83 +188,137 @@ public void checkDateTimeClash(ArrayList<Task> taskList, Task taskToCheck)
...
                     && hasTimeClash(task, taskToCheck.getDoOnStartDateTime(), taskToCheck.getDoOnEndDateTime())) {
-                throw new TimeClashException(task);
+                throw new TimeClashException(ERROR_SCHEDULE_CLASH_MESSAGE + "\nClashing task: " + task);
             }
         }
     }
 
+    private void checkTask(Task newTask) throws InvalidInputException {
+        if (newTask.getDoOnStartDateTime().isBefore(LocalDateTime.now())) {
+            throw new InvalidInputException(ERROR_START_DATE_IN_THE_PAST_MESSAGE);
```
Comment (jltha) [inline src/main/java/seedu/sherpass/task/TaskList.java:198]: If you'd like, I think you can put this in the checkDateTimeClash() method.

File: src/main/java/seedu/sherpass/task/TaskList.java [hunk 4]
```diff
@@ -179,83 +188,137 @@ public void checkDateTimeClash(ArrayList<Task> taskList, Task taskToCheck)
         for (Task task : taskList) {
             if (isOnSameDay(task.getDoOnStartDateTime(), taskToCheck.getDoOnStartDateTime())
                     && hasTimeClash(task, taskToCheck.getDoOnStartDateTime(), taskToCheck.getDoOnEndDateTime())) {
-                throw new TimeClashException(task);
+                throw new TimeClashException(ERROR_SCHEDULE_CLASH_MESSAGE + "\nClashing task: " + task);
             }
         }
     }
 
+    private void checkTask(Task newTask) throws InvalidInputException {
```
Comment (jltha) [inline src/main/java/seedu/sherpass/task/TaskList.java:196]: If you intend to keep this if-else, you'll need to add another else as part of the [coding standards](https://se-education.org/guides/conventions/java/basic.html#layout).

File: src/main/java/seedu/sherpass/task/TaskList.java (hunk 2 above)
Comment (thedarie) [reply src/main/java/seedu/sherpass/task/TaskList.java:203]: ok, thanks! this was added before your pr was merged. i'll remove it

File: src/main/java/seedu/sherpass/task/TaskList.java (hunk 3 above)
Comment (thedarie) [reply src/main/java/seedu/sherpass/task/TaskList.java:198]: got it, will do that. thanks!

File: src/main/java/seedu/sherpass/task/TaskList.java (hunk 4 above)
Comment (thedarie) [reply src/main/java/seedu/sherpass/task/TaskList.java:196]: err i think you may have highlighted the wrong line, can you edit it?

Comment (jltha) [reply src/main/java/seedu/sherpass/task/TaskList.java:196]: I couldn't highlight that part cuz I already highlighted it in my previous comments, but just a brief summary of your method body:
 
```
If (cond 1) {

} else if (cond 2) {

} else if (cond 3) {

}
```

There should be another else statement after the last else-if

Comment (thedarie) [reply src/main/java/seedu/sherpass/task/TaskList.java:196]: got it. thanks!

**Review by yuzhongng — APPROVED** [review]

**Review by yuzhongng — APPROVED** [review]

**Review by laiisaac — APPROVED** [review]

**Review by yuzhongng — APPROVED** [review]

**Review by BradenTeo — APPROVED** [review]

**Review by jltha — APPROVED** [review]
