### PR TITLE
Fix checking of date and time clash

### LINKED ISSUE #95: Fix checking of date and time clash
To add junit tests and find out why the bug occured, i.e. some test cases with time clash were being added in the task when editing of a task occurs.

Test case (Only instructions available:)
add testing3 /do 1/4/2022 /start 11:00 /end 12:00 /repeat WEEKLY
edit 8 /do 18/5/2022 /start 10:00 /end 12:00 /repeat
edit 9 /do 18/05/2022 /start 11:00 /end 12:00 /by 30/5/2022

### PR DESCRIPTION
**Pull request by jltha**
Add junit tests for checking of date and time clash, as well as cleaning some code in timetable

Also fixed code which were reflected from the PE dry run

resolves #95 #113 #97 #133 #123  #127 #98 #119 #104 #111

### CODE REVIEW

**Review by thedarie — APPROVED** [review]

**Review by yuzhongng — APPROVED** [review]

File: src/main/java/seedu/sherpass/timer/TimerLogic.java [hunk 1]
```diff
@@ -236,10 +232,7 @@ public boolean isTimerPausedOrStopped() {
         if (!timer.isTimerRunning()) {
             return true;
         }
-        if (timer.isTimerPaused()) {
-            return true;
-        }
-        return false;
+        return timer.isTimerPaused();
```
Comment (laiisaac) [inline src/main/java/seedu/sherpass/timer/TimerLogic.java:235]: Thanks for refactoring this part, was unsure if this was the best way to do it

**Review by laiisaac — APPROVED** [review]
